### ISSUE TITLE
You should consider adding some pretty fonts :)

### ISSUE THREAD

**Issue by netbrain** [AOG-88/aog-88.github.io#1]
https://www.awwwards.com/20-best-web-fonts-from-google-web-fonts-and-font-face.html

![bitmoji](https://render.bitstrips.com/v2/cpanel/a94a1c04-3f49-4c24-bfb9-e9e545c98738-2811338b-aad0-4f64-badb-e790d1737221-v1.png?transparent=1&palette=1&width=246)

**Comment by AOG-88** [comment]
thanks! done :)
